### ISSUE TITLE
搭建一个网站吧！

### ISSUE THREAD

**Issue by xcatliu** [hylerrix/deno-tutorial#3]
要不要使用 [Pagic](https://github.com/xcatliu/pagic) 搭建一个网站？若 @hylerrix 同意的话，我可以帮忙完成第一版的工作😊

Pagic 是用 Deno 实现的一个静态网站生成器，这是第一个使用 Pagic 搭建的网站：
https://ts.xcatliu.com/

特性：
- github actions 持续集成发布
- 静态网页 + 单页应用——页面初次加载性能最优，页面间跳转时能无缝跳转
- 深色模式
- gitalk 评论
- 更多功能开发中

**Comment by esmadrider** [comment]
好啊！主题好棒，那麻烦了~ 你先来提交个 Pagic 基础骨架，我来调试部署 😁

**Comment by xcatliu** [comment]
#4

**Comment by xcatliu** [comment]
看日志已经成功触发了 github actions 哦
https://github.com/hylerrix/deno-tutorial/actions

[oa-pages](https://github.com/hylerrix/deno-tutorial/tree/gh-pages) 分支已经有内容了，不过 CNAME 还没配对

**Comment by esmadrider** [comment]
感谢 @xcatliu 的贡献！上线咯，http://deno-tutorial.js.org/。
还有点 Google Analytics 的问题期待 Pagic 的更新~
